/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./WebIde.Frontend/Views/**/*.cshtml",
    "./WebIde.Frontend/Areas/**/*.cshtml",
    "./WebIde.Frontend/wwwroot/js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                  "#2752c7",
        "on-primary":               "#f1f2ff",
        "primary-container":        "#7f9bff",
        "on-primary-container":     "#001c5f",
        "secondary":                "#b60055",
        "on-secondary":             "#ffeff1",
        "secondary-container":      "#ffc1ce",
        "on-secondary-container":   "#900042",
        "tertiary":                 "#106b00",
        "on-tertiary":              "#d3ffc0",
        "tertiary-container":       "#32ff00",
        "on-tertiary-container":    "#0c5c00",
        "background":               "#f6f6f6",
        "surface":                  "#f6f6f6",
        "surface-bright":           "#f6f6f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f1f1f1",
        "surface-container":        "#e8e8e8",
        "surface-container-high":   "#e2e2e2",
        "surface-container-highest":"#dddddd",
        "surface-variant":          "#dddddd",
        "on-surface":               "#2f2f2f",
        "on-background":            "#2f2f2f",
        "on-surface-variant":       "#5b5b5b",
        "outline":                  "#777777",
        "outline-variant":          "#adadad",
        "error":                    "#b41340",
        "error-container":          "#f74b6d",
        "on-error":                 "#ffefef",
        "on-error-container":       "#510017",
        "inverse-surface":          "#0e0e0e",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm:      "0px",
        md:      "0px",
        lg:      "0px",
        xl:      "0px",
        "2xl":   "0px",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
