/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#001e2c',
        'on-primary-fixed': '#002113',
        'on-tertiary-container': '#af6f00',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary-fixed': '#2a1700',
        'secondary-container': '#00a6e0',
        'on-surface': '#dae2fd',
        'inverse-primary': '#006c49',
        'on-primary-fixed-variant': '#005236',
        'primary-container': '#00150b',
        outline: '#8f9095',
        'surface-variant': '#2d3449',
        'on-tertiary': '#472a00',
        'secondary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#4edea3',
        'tertiary-container': '#1c0e00',
        'tertiary-fixed': '#ffddb8',
        'on-error': '#690005',
        surface: '#0b1326',
        'on-secondary-fixed-variant': '#004c69',
        'on-secondary-container': '#00374d',
        background: '#0b1326',
        'surface-container-lowest': '#060e20',
        primary: '#4edea3',
        'error-container': '#93000a',
        'surface-bright': '#31394d',
        'inverse-surface': '#dae2fd',
        'surface-dim': '#0b1326',
        error: '#ffb4ab',
        'surface-container-low': '#131b2e',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#7bd0ff',
        'surface-tint': '#4edea3',
        'surface-container': '#171f33',
        'inverse-on-surface': '#283044',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary-container': '#008e62',
        tertiary: '#ffb95f',
        'primary-fixed': '#6ffbbe',
        'on-primary': '#003824',
        'on-surface-variant': '#c6c6cb',
        'surface-container-high': '#222a3d',
        'on-background': '#dae2fd',
        'on-secondary': '#00354a',
        secondary: '#7bd0ff',
        'surface-container-highest': '#2d3449',
        'outline-variant': '#45474b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['Fira Code', 'JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};

